#!/usr/bin/env python3
"""Builds the tutorial module and its preview page.

tutorial.js  - the module the game includes after assets.js (engine + clips + player)
index.html   - the preview page (art kit + tutorial.js inlined), published as an Artifact
"""
import pathlib
here = pathlib.Path(__file__).resolve().parent
src = here / 'src'
parts = ['engine.js', 'clips-basics.js', 'clips-antigens.js', 'player.js']
# Everything is wrapped in one function scope so nothing leaks into the page that inlines it (v3, the Sandbox);
# the only global is window.CytoTutorial (set in player.js).
bundle = ('// Cytostorm tutorial clips. Generated by tutorial/build.py from tutorial/src; edit those files.\n(function () {\n'
          + '\n'.join((src / p).read_text() for p in parts if (src / p).exists()) + '\n})();\n')
(here / 'tutorial.js').write_text(bundle)
art = (here.parent / 'prototype' / 'assets' / 'assets.js').read_text()
page = (src / 'preview.html').read_text().replace('/*BUNDLE*/', art + '\n' + bundle)
(here / 'index.html').write_text(page)
print('tutorial.js', len(bundle), 'bytes; index.html', len(page), 'bytes')
