#!/usr/bin/env python3
"""Re-fork the workshop UI from v3: copies prototype/v3/src/ui.js and template.html (owned by the build
thread, read-only here) and applies the workshop changes, writing src/ui.js and src/template.html.
Big workshop blocks live in src/ui-blocks.js. Every anchor is asserted, so if v3 moves something this
fails loudly and names the anchor. Usage: python3 fork_ui.py && python3 build.py"""
import pathlib, re
here = pathlib.Path(__file__).parent
import os
# V3SRC=<folder> forks from a frozen release (e.g. prototype/v3/releases/v26) instead of live src
v3 = pathlib.Path(os.environ['V3SRC']).resolve() if os.environ.get('V3SRC') else here.parent / 'prototype/v3/src'
print('forking from', v3)
s = (v3 / 'ui.js').read_text()
t = (v3 / 'template.html').read_text()
blocks = dict(re.findall(r'//@@ (\w+)\n(.*?)(?=//@@ |\Z)', (here / 'src/ui-blocks.js').read_text(), re.S))

def rep(text, a, b, count=1):
    n = text.count(a)
    assert n == count, f'anchor found {n} times (want {count}): {a[:90]!r}'
    return text.replace(a, b)
def ui(a, b, count=1):
    global s; s = rep(s, a, b, count)
def tp(a, b):
    global t; t = rep(t, a, b)
def between(text, a, b, new):
    i = text.index(a); j = text.index(b, i)
    return text[:i] + new + text[j:]

# ---- ui.js ----
ui("// Immune RTS prototype v3: rendering, input, HUD, production cards, storm,\n// guide, dev tools.",
   "// Mechanics workshop UI: generated by workshop/fork_ui.py from prototype/v3/src/ui.js.\n// Do not edit by hand; edit fork_ui.py or src/ui-blocks.js. v3: rendering, input, HUD, production cards, storm,\n// guide, dev tools.")
s = s.replace("'immuneRtsV3.", "'immuneWorkshopV3.")
ui("  let levelKey = LEVELS[store.get('immuneWorkshopV3.level')] ? store.get('immuneWorkshopV3.level') : 'papercut';",
"""  // workshop: the dev setup (spawn rates, cheats, toggles) and its own tunables
  mergeWs(store.get('immuneWorkshopV3.ws'));
  const dev = Object.assign(defaultDev(), store.get('immuneWorkshopV3.dev') || {});
  if ((dev.ver || 0) < 2) { dev.toxinLoad = false; dev.ver = 2; } // toxin went optional and off (Alex, 2026-10-07): reset older saved setups once
  if (dev.ver < 3) { if (dev.leakZone === '2') dev.leakZone = '3'; dev.ver = 3; } // four sectors (2026-10-08): the Lymph node moved from 2 to 3
  if (dev.ver < 4) { for (const u in dev.friendly) dev.friendly[u] = Math.min(90, (dev.friendly[u] || 0) * 3); dev.ver = 4; } // V28: x3 units, so extra cells x3 too (antigen groups are already x3)
  dev.rates = Object.assign(ZERO_RATES(), dev.rates); dev.friendly = Object.assign(defaultDev().friendly, dev.friendly);
  if (!LEVELS[dev.level]) dev.level = 'sandbox';
  let levelKey = dev.level;
  let ws = null, pendingSetup = null;
  const saveDev = () => store.set('immuneWorkshopV3.dev', dev);""")
# Measles (workshop-only virus) art and names
ui("virus: { art: 'herpes', marker: 'herpes' },", "virus: { art: 'herpes', marker: 'herpes' }, measles: { art: 'pollen', marker: 'herpes' }, /* workshop: Measles, placeholder art */")
ui("  const kindName = k => (KINDS[k] ? KINDS[k].name : k);", "  const kindName = k => (k === 'measles' ? 'Measles' : KINDS[k] ? KINDS[k].name : k);")
ui("    bodySprite('herpes', C.herpes.radius * 1.3);", "    bodySprite('herpes', C.herpes.radius * 1.3);\n    bodySprite('pollen', WS.measles.radius * 1.4); // workshop: Measles")
ui("    glowDot('lilac', 'rgba(185,166,255,0.9)', 2);", "    glowDot('lilac', 'rgba(185,166,255,0.9)', 2);\n    glowDot('puddle', 'rgba(150,200,40,0.5)', 5); // workshop: toxin puddles")
ui("        case 'breach': toast('Antigens reached the Lymph node', 'bad'); break;",
"""        case 'breach': toast('Antigens reached the Lymph node', 'bad'); break;
        case 'nearLoss': { const o = ORGANS.find(x => x.k === f.cause); toast(`No death: ${o ? o.name + ' at 0' : 'Host failure'} skipped. It keeps its worst penalty.`, 'bad'); break; }""")
ui("        case 'nkPop': burstParts(f.u, f.v, 'lilac', 6, 50, 0.4); break;",
"""        case 'nkPop': burstParts(f.u, f.v, 'lilac', 6, 50, 0.4); break;
        case 'hijack': toastOnce('hijack', 'Measles hijacked a macrophage: it goes dark, then bursts. NK cells pop it first', 'bad'); break;
        case 'measlesBurst': burstParts(f.u, f.v, 'lilac', 10, 70, 0.5); break;""")
ui("    // Fields under everything: slime domes, nets, Support rings",
"""    // workshop: toxin puddles on the floor
    for (const p of ws.tox.puddles) draw('puddle', p.u, p.v, null, Math.min(1, p.life / p.max * 1.4) * 0.9, p.r / 10);
    // Fields under everything: slime domes, nets, Support rings""")
ui("      if (a.flash > 0) al *= 0.6;\n      switch (a.k) {\n", "      if (a.flash > 0) al *= 0.6;\n      if (a.hj) draw('pollen', a.u, a.v, a.rot, al, mul); // workshop: Measles\n      else switch (a.k) {\n")
ui("        const name = c.tb ? 'macrophage-infected' : c.mode === 'support' ? 'macrophage-support' : 'macrophage-offense';\n        const stunA = c.stun > 0 ? 0.5 + 0.3 * Math.sin(ts * 20) : 1;",
   "        const name = c.tb || (c.hj && Math.floor(ts / 0.3) % 2) ? 'macrophage-infected' : c.mode === 'support' ? 'macrophage-support' : 'macrophage-offense';\n        const stunA = c.hj ? 0.45 : c.stun > 0 ? 0.5 + 0.3 * Math.sin(ts * 20) : 1;")
_pa = next(x for x in ("    const W = w / dpr, H = h / dpr, D = game.duration;\n", "    const W = w / dpr, H = h / dpr, bh = 10, pad = 14, D = game.duration;\n") if x in s)
ui(_pa, _pa + blocks['prog'])
i = s.index("    $('#cellCount').textContent") if "    $('#cellCount').textContent" in s else s.index("    const cc = $('#cellCount');"); j = s.index('\n', i) + 1
s = s[:j] + blocks['hud'] + s[j:]
ui("    else if (g.zones[LYMPH].count > 0) {",
   "    else if (dev.toxinLoad && !dev.toxinSimple && ws.tox.load >= 50) { cls = 'bad'; html = `<b>Toxins are piling up.</b> Your tired liver and kidneys can't keep up, and it's adding fatigue. Rest to clear it, or swallow instead of shooting.`; }\n    else if (g.zones[LYMPH].count > 0) {")
# v3 version 7 put its tutorial-clip helpers between showStart and guideHtml; keep them (the guide's "How to play" tab uses TUT)
s = between(s, "  function showStart() {", "  // ---- tutorial clips" if "  // ---- tutorial clips" in s else "  function guideHtml(tab) {", blocks['start'])
ui("      unit('tapeworm-head', 'Tapeworm',",
"""      unit('pollen', 'Measles (workshop only)', 'The hijacker. Swims to the nearest macrophage and takes it over.', [`The macrophage goes dark (no ring, no eating) for ${WS.measles.incubate} s, then bursts into ${WS.measles.burst} more. Swallowing one infects the macrophage too.`, 'NK cells pop hijacked macrophages before they burst. One hit kills Measles itself.']),
      unit('tapeworm-head', 'Tapeworm',""")
ui("        <li><b>Pause</b>: the II button, or Space.",
"""        <li><b>Workshop</b> (top right): pick a combo or a real level, set spawn rates for antigens and your cells, turn on cheats, and change any number live.</li>
        <li><b>Toxin load</b> (when on, the blood vessel turns green as it builds, and a green strip on the organ button shows the level; with Organ health off it gets its own bar): shots, nets and the storm fill it; swallows don't. Your liver and kidneys clear it fast when you're rested and slowly when you're tired, and whatever is left feeds the heart. With Toxin puddles on, kills over the mark leave green puddles that slow your cells.</li>
        <li><b>Leakers in the Sandbox</b>: the liver and kidneys are also drawn in the blood vessel at the Lymph node end. Each Hepatitis or E. coli that reaches the blood adds ${Math.round(WS.leakers.leak * 100)}% to that organ's breach clock. With Toxin load on, they also clear toxin (liver ${Math.round(WS.organs.liverShare * 100)}%, kidneys the rest), toxin over ${WS.organs.kidneyToxAt} wears the kidneys down, and a green strip under the organ button shows the level.</li>
        <li><b>Pause</b>: the II button, or Space.""")
# end screen: keep going, levels go through the workshop
ui("""      <div class="btnrow">${r.win && nextKey ?""", """      ${!r.win ? '<div class="btnrow"><button class="btn primary" id="keepGoing" type="button">Keep going with No death</button></div>' : ''}
      <div class="btnrow">${r.win && nextKey ?""")
ui("    $('#levelsBtn').addEventListener('click', () => { newGame(); showStart(); });",
"""    $('#levelsBtn').addEventListener('click', () => { newGame(); showStart(); });
    if ($('#keepGoing')) $('#keepGoing').addEventListener('click', () => {
      dev.noDeath = true; saveDev();
      ws.forgive(); endShown = false; collapseT = 0; closeModal(); syncWorkshop();
    });""")
ui("    if ($('#next')) $('#next').addEventListener('click', () => { levelKey = nextKey; store.set('immuneWorkshopV3.level', levelKey); newGame(); showStart(); });",
   "    if ($('#next')) $('#next').addEventListener('click', () => { pickLevel(nextKey); });")
# the game runs through the workshop layer
ui("    game = new Game(levelKey, seed);\n", """    levelKey = dev.level;
    ws = new Workshop(dev, seed); game = ws.game;
    const c = pendingSetup;
    if (c) {
      if (c.mix) for (let z = 0; z < NZ; z++) game.setMix(z, c.mix);
      if (c.zones) c.zones.forEach((m, z) => game.setZone(z, m));
      if (c.output != null) game.setOutput(c.output);
      if (c.boss) ws.spawnGroup('worm');
      if (c.organs) for (const k in c.organs) ws.setOrgan(k, c.organs[k]);
      if (c.fatigue != null) game.fatigue = c.fatigue;
    }
""")
ui("    closeSheet(); buildCards();\n    hud();\n  }", "    closeSheet(); buildCards();\n    hud(); syncWorkshop();\n  }")
# the step loop: v3 later added its own dev spawner (devSpawn) and a MAX_STEPS cap (V28); keep whatever is there, step through the workshop
_m = re.search(r"      while \(acc >= STEP && n < (16|MAX_STEPS)\) \{ (devSpawn\(STEP\); )?game\.step\(STEP\); acc -= STEP; n\+\+; \}", s)
assert _m, 'step loop anchor'
ui(_m.group(0), f"      while (acc >= STEP && n < {_m.group(1)} && !game.result) {{ {_m.group(2) or ''}ws.step(STEP); acc -= STEP; n++; }}")
ui("  $('#devStep').addEventListener('click', () => { if (game && !game.result) for (let i = 0; i < 60; i++) game.step(STEP); });",
   "  $('#devStep').addEventListener('click', () => { if (game && !game.result) for (let i = 0; i < 60 && !game.result; i++) ws.step(STEP); });")
ui("  $('#devSkip').addEventListener('click', () => { if (game && !game.result) for (let i = 0; i < 900 && !game.result; i++) game.step(STEP); });",
   "  $('#devSkip').addEventListener('click', () => { if (game && !game.result) for (let i = 0; i < 900 && !game.result; i++) ws.step(STEP); });")
ui("""  $('#devBtn').addEventListener('click', () => { $('#dev').hidden = !$('#dev').hidden; });
  $('#devClose').addEventListener('click', () => { $('#dev').hidden = true; });""",
"""  const setDevOpen = open => { $('#dev').hidden = !open; document.body.classList.toggle('ws-open', open); $('#devBtn').classList.toggle('on', open); requestAnimationFrame(resize); if (open) syncWorkshop(); };
  $('#devBtn').addEventListener('click', () => setDevOpen($('#dev').hidden));
  $('#devClose').addEventListener('click', () => setDevOpen(false));""")
s = between(s, "  function buildTuning() {", "  $('#tuneCopy')", blocks['tuning'])
ui("JSON.stringify(tuningDiff(), null, 1)", "JSON.stringify({ tune: tuningDiff(DEFAULTS, CONFIG), ws: tuningDiff(WS_DEFAULTS, WS) }, null, 1)")
panel = blocks['panel'].replace('/*NEWMECH*/', blocks.get('newmech', ''))
ui("  // ---- boot ----", panel + "  // ---- boot ----")
ui("  buildTuning();\n  $('#seed').value = seed;", "  buildTuning();\n  buildWorkshop();\n  $('#seed').value = seed;")
ui("  newGame();\n  showStart();\n  requestAnimationFrame(frame);", "  pendingSetup = dev.level === 'sandbox' && dev.combo ? COMBOS[dev.combo] || null : null;\n  newGame();\n  showStart();\n  requestAnimationFrame(frame);")

ui("const infected = g.cells.filter(c => c.infected).length;", "const infected = g.cells.filter(c => c.infected && !c.hj).length; // workshop: Measles-hijacked macrophages aren't neutrophils")

# the Sandbox level never ends (duration 1e9), so the end graph's time axis must use the match length
ui("    const T = Math.max(game.duration, game.t), maxY", "    const T = game.duration > 1e6 ? Math.max(game.t, 1) : Math.max(game.duration, game.t), maxY") # workshop: Sandbox has no end time

# organ health: liver and kidneys in the vessel, toxin tint, leaker art and banners
ui("measles: { art: 'pollen', marker: 'herpes' },", "measles: { art: 'pollen', marker: 'herpes' }, hep: { art: 'hepatitis', marker: 'hepatitis' }, ecoli: { art: 'e-coli', marker: 'e-coli' },")
ui("  const kindName = k => (k === 'measles' ? 'Measles' : KINDS[k] ? KINDS[k].name : k);", "  const kindName = k => (k === 'measles' ? 'Measles' : k === 'hep' ? 'Hepatitis' : k === 'ecoli' ? 'E. coli' : KINDS[k] ? KINDS[k].name : k);")
ui("    glowDot('puddle', 'rgba(150,200,40,0.5)', 5); // workshop: toxin puddles", "    glowDot('puddle', 'rgba(150,200,40,0.5)', 5); // workshop: toxin puddles\n    glowDot('jaundice', 'rgba(255,214,60,0.75)', 4.5); glowDot('ecoliGlow', 'rgba(120,230,170,0.6)', 4.5); // workshop: leakers\n    for (const n of ['liver', 'kidneys']) for (const st of ORGAN_STATE) bodySprite(`${n}-${st}`, 19); // workshop: organs in the vessel (art kit v8 states)\n    bodySprite('leak-splat', 10); bodySprite('hepatitis', 4); bodySprite('e-coli', 6.5); bodySprite('e-coli-dividing', 7.3);")
ui("      if (a.hj) draw('pollen', a.u, a.v, a.rot, al, mul); // workshop: Measles\n      else switch (a.k) {\n",
   "      if (a.hj) draw('pollen', a.u, a.v, a.rot, al, mul); // workshop: Measles\n      else if (a.leak === 'liver') draw('hepatitis', a.u, a.v, a.rot, al, mul); // workshop: Hepatitis\n      else if (a.leak === 'kidney') { // workshop: E. coli, pinched in two for the last second before it divides\n        const en = a.ediv < 1 && Math.floor(a.ediv * 8) % 2 === 0 ? 'e-coli-dividing' : 'e-coli', er = Math.atan2(a.vv, a.vu);\n        draw(en, a.u, a.v, er, al, mul);\n        if (a.flash > 0) { ctx.save(); ctx.globalCompositeOperation = 'lighter'; draw(en, a.u, a.v, er, al * 0.8, mul); ctx.restore(); }\n      }\n      else switch (a.k) {\n")
ui("    // Fields under everything: slime domes, nets, Support rings", blocks['organs'] + "    // Fields under everything: slime domes, nets, Support rings")
ui("  function burstParts(u, v, kind, n, speed, life) {", blocks['organfns'] + "  function burstParts(u, v, kind, n, speed, life) {")
ui("        case 'measlesBurst': burstParts(f.u, f.v, 'lilac', 10, 70, 0.5); break;",
   """        case 'measlesBurst': burstParts(f.u, f.v, 'lilac', 10, 70, 0.5); break;
        case 'leak': { const [lu, lv] = ORGAN_AT[f.organ][0]; burstParts(lu, lv, f.organ === 'liver' ? 'jaundice' : 'ecoliGlow', 6, 40, 0.5);
          toastOnce('leak-' + f.organ, f.organ === 'liver' ? 'Hepatitis reached the blood: the liver took a hit' : 'E. coli reached the blood: the kidneys took a hit', 'bad'); break; }
        case 'organFail': if (!game.result && !dev.noDeath) toast(`${(ORGANS.find(o => o.k === f.organ) || { name: f.organ }).name} failed (Immortal is on, so the match goes on)`, 'bad'); shake = Math.max(shake, 0.4); break;""")

# leakers ride flu and staph bodies: keep them out of those hints and out of the Lymph node warning, and give them their own hint
ui("    const has = k => g.ag.some(a => a.k === k && !a.dead);", "    const has = k => g.ag.some(a => a.k === k && !a.dead && !a.leak); // workshop: leakers aren't flu or Staph\n    const leakers = g.ag.filter(a => a.leak && !a.dead && !a.eaten);")
ui("    else if (g.zones[LYMPH].count > 0) {", "    else if (leakers.length && !g.zones[LYMPH].count) { html = leakers.some(a => a.leak === 'liver') ? `<b>Hepatitis is swimming for the left blood vessel.</b> Each one that gets in adds ${Math.round(WS.leakers.leak * 100)}% to the liver's breach clock. Nets catch the swarm in the zone it crosses.` : `<b>E. coli is swimming for the left blood vessel.</b> Each one that gets in adds ${Math.round(WS.leakers.leak * 100)}% to the kidneys' breach clock.${dev.toxinLoad ? ' Shooting it dumps toxin: Offense macrophages swallow it clean.' : ' It takes 2 hits, or one swallow.'}`; }\n    else if (g.zones[LYMPH].count > 0) {") # workshop: leakers head for the vessel

ui("        const warn = KINDS[a.k].divides && a.age < a.div && a.div - a.age < BLINK_WARN && a.div - a.age > 0;\n        const tm = a.blink > 0 ? a.blink : warn ? a.div - a.age : -1;",
   "        const ewarn = a.leak === 'kidney' && a.ediv > 0 && a.ediv < BLINK_WARN; // workshop: E. coli keeps its own division clock\n        const warn = ewarn || (KINDS[a.k].divides && a.age < a.div && a.div - a.age < BLINK_WARN && a.div - a.age > 0);\n        const tm = a.blink > 0 ? a.blink : warn ? (ewarn ? a.ediv : a.div - a.age) : -1;")

# guide: the Sandbox-only system clips (Fatigue and toxins) under How to play, and the leakers and organs
ui("${TUT.ANTIGENS.filter(id => TUT.CLIPS[id]).map(btn).join('')}</div>`;",
   "${TUT.ANTIGENS.filter(id => TUT.CLIPS[id]).map(btn).join('')}${(TUT.SYSTEMS || []).some(id => TUT.CLIPS[id]) ? `<h4>Systems</h4>${TUT.SYSTEMS.filter(id => TUT.CLIPS[id]).map(btn).join('')}` : ''}</div>`;")
ui("      unit('tapeworm-head', 'Tapeworm',",
   "      unit('hepatitis', 'Hepatitis (workshop only)', 'The liver leaker. Fast swarms of 18, one hit kills.', [`Swims for the left blood vessel. Each one that gets in adds ${Math.round(WS.leakers.leak * 100)}% to the liver's breach clock. Net neutrophils catch the swarm.`]),\n      unit('e-coli', 'E. coli (workshop only)', 'The kidney leaker. Takes 2 hits and divides.', [`Each one that reaches the blood adds ${Math.round(WS.leakers.leak * 100)}% to the kidneys' breach clock. ${dev.toxinLoad ? 'Shooting it dumps extra toxin; <b>swallowing it is the clean answer</b>.' : 'Swallowing it is the quickest answer.'}`]),\n      unit('tapeworm-head', 'Tapeworm',")

ui("      <div class=\"bodyview\">${ORGANS.map(card).join('')}</div>", "      <div class=\"bodyview\">${wsToxCard()}${ORGANS.map(card).join('')}</div>") # workshop: toxin and leaks

# ---- template.html ----
t = re.sub(r'<title>[^<]*</title>', '<title>Mechanics Workshop</title>', t, count=1)
tp('<button id="devBtn" class="hbtn" type="button">Dev</button>', '<button id="wsReset" class="hbtn" type="button" aria-label="Reset: restart this setup from zero">Reset</button><button id="devBtn" class="hbtn" type="button">Workshop</button>')
tp('<span id="cellCount">0 cells</span></div>', '<span id="cellCount">0 cells</span></div>\n      <div class="fatigue toxrow" id="toxRow"><span>Toxin</span><div class="toxbar"><i id="toxFill"></i><b id="toxMark"></b></div><span id="toxVal">0</span></div>')
tp('<aside id="dev" hidden aria-label="Dev tools">', '<aside id="dev" hidden aria-label="Workshop">')
tp('  <h3>Dev tools <button type="button" class="hbtn" id="devClose">Close</button></h3>', '  <h3>Workshop <button type="button" class="hbtn" id="devClose">Close</button></h3>\n  <div id="wsPanel"></div>')
tp('    <span>Tuning <small', '    <span>Every number <small')
tp('  --toxin: #B45CFF;', '  --toxin: #B45CFF;\n  --slime: #96C828;')
tp('/* Narrower screens', (here / 'src/workshop.css').read_text() + '\n/* Narrower screens')
tp('<script>\n/*UI*/', '<script>\n/*LAYER*/\n</script>\n<script>\n/*COMBOS*/\n</script>\n<script>\n/*UI*/')

(here / 'src/ui.js').write_text(s)
(here / 'src/template.html').write_text(t)
print(f'forked ui.js ({len(s) // 1024} KB) and template.html from v3')
